### ISSUE TITLE
problem: discrepancy between completed problems and actual completed problems

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/Emurgis#296] opened 2018-06-19 00:57 UTC
problem: on the statistics page the total number of completed problems does not match the number of solved problems listed on the user's profile.

solution: I haven't checked where the numbers come from (completed problems) but it should match the total number of problems that user has solved (as listed on the user's profile page).

Probably should change the name to "solved problems" too instead of "completed problems".

**Comment by geekyd** [comment] 2018-06-19 03:52
@emurgobot claim

**Comment by geekyd** [comment] 2018-06-19 07:00
@gazhayes I have looked into some cases where the user stats can be incorrect in the stats page. If a user claimed an issue & the owner deletes it or a user solved the issue & the owner closes it.

In either case the problems won't show up on the profile page as it makes direct query. In case of stats it will still show up. 

There are a few solutions that we can follow here:
- Replace hard delete with soft delete
- Remove all the context of users related to problems from userStats API if the problem is deleted.

What do you think?

**Comment by gazhayes** [comment] 2018-06-19 09:09
Do the 2nd one, but at the same time, it has to be **very** clear that deleting it means that the problem was not solved, instead it was circumvented (found out after discussion that it's not actually a problem). In fact, we should replace "delete" with something like "oops, I thought this was a problem but it's actually not a problem".


So just to be clear: when a owner marks a problem as solved, it currently adds this to the user stats?

**Comment by gazhayes** [comment] 2018-06-19 10:01
Actually now I'm confused, but I think you've got it under control.

If a an owner deletes their problem without marking it as solved, no stats should be added. But the stats show more resolved problems than actually exist so I assume that when an owner deletes a problem it *is* being added to stats but it shouldn't be.

**Comment by geekyd** [comment] 2018-06-19 10:17
Yes, actually user can delete the problem even if it is marked as solved. When that happens the user stats are not updated. This is why the stats show more problems the user solved. So I will update the stats in case of deletion & hide the delete button when the problem is marked as solved by the owner.

This will solve this edge case.

**Comment by geekyd** [comment] 2018-06-19 10:35
Done in #311 

@emurgobot remove "in progress"
@emurgobot label "done"

**Closed** 2018-06-19 13:08 UTC
Labels: done
